### ISSUE TITLE
Scanner crash: panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by SlavikCA** [viktorstrate/photoview#33]
While scanning personal photo library, the scanner crashed on this photo:

[DSC05995.zip](https://github.com/viktorstrate/photoview/files/4485288/DSC05995.zip)

> 2020/04/16 06:32:51 Scanning directory: /photos/2005/2005 01 Ivan Reception
> 2020/04/16 06:32:51 Scanning image: /photos/2005/2005 01 Ivan Reception/DSC05995.JPG
> 2020/04/16 06:32:51 Scanning for EXIF
> panic: runtime error: slice bounds out of range [:6] with capacity 0
> 
> goroutine 40820 [running]:
> github.com/xor-gate/goexif2/mknote.(*nikonV3).Parse(0xebce00, 0xc00d722b40, 0x0, 0x0)
>         /go/pkg/mod/github.com/xor-gate/goexif2@v1.1.0/mknote/mknote.go:58 +0x268
> github.com/xor-gate/goexif2/exif.Decode(0xaec1c0, 0xc00d136db0, 0x2, 0x2, 0xe81520)
>         /go/pkg/mod/github.com/xor-gate/goexif2@v1.1.0/exif/exif.go:331 +0x282
> github.com/viktorstrate/photoview/api/scanner.ScanEXIF(0xc00d62cf80, 0xc00d6788c0, 0x0, 0x0, 0x1)
>         /app/scanner/exif.go:42 +0x280
> github.com/viktorstrate/photoview/api/scanner.ScanPhoto(0xc00d62cf80, 0xc0000a0120, 0x30, 0x118, 0xc006452160, 0x8, 0x0, 0x4, 0xae8600, 0xc00d6d0840)
>         /app/scanner/photo_scanner.go:47 +0x4ed
> github.com/viktorstrate/photoview/api/scanner.scan(0xc00015da40, 0xc00acdd600)
>         /app/scanner/album_scanner.go:193 +0x1081
> created by github.com/viktorstrate/photoview/api/scanner.ScanUser
>         /app/scanner/album_scanner.go:95 +0x1ef
> 2020/04/16 06:32:55 No .env file found
> 2020/04/16 06:32:55 Connecting to database: photoview:photo-secret@tcp(db)/photoview?multiStatements=true&parseTime=true
> 2020/04/16 06:32:55 Database is up to date

I understand, that some images can be corrupt / has invalid EXIF info.
I think in such cases, scanning should skip just one image and continue with the rest.
The image above stopped the scanner in such a manner, that it didn't continue.

**Comment by SlavikCA** [comment]
can that bug be the reason, that all albums (even successfully scanned) are shown as empty?
For example:
http://pix.slavikf.com:2010/share/ag1NE6Pf
